version: "3.5"
services:
  jupyter-lab:
    build: .
    ports: 
      - 8888:8888
      # ローカルでマウントするフォルダ
    volumes: 
      - '.:/work_space'
      # -itの部分
    tty: true
    stdin_open: true
    # イメージ名を記述
    image: mecab-love
    # コンテナ名を記述
    container_name: mecab-jupyter-love